---
title: "Figure2"
author: "Joanna Kaplanis and Kaitlin Samocha"
date: "27/08/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#get bootstrap CIs on all mean ratios
bootRatioCI <- function(x,y,nsim = 100){
  x <- x[!is.na(x)]
  y <- y[!is.na(y)]
  simx <- replicate(nsim,mean(sample(x, size = length(x),replace = T)))
  simy <- replicate(nsim,mean(sample(y, size = length(y),replace = T)))
  cis <- quantile(simx/simy,probs = c(0.025,0.975),na.rm = T)
  return(cis)
}

meanbootCI <- function(x,nsim = 100){
  x <- x[!is.na(x)]
  simx <- replicate(nsim,mean(sample(x, size = length(x),replace = T)))
  cis <- quantile(simx,probs = c(0.025,0.975))
  return(cis)
}

getmeanbootCIs <- function(mycol,df,nsim = 100){
  conv = df[df$diag_group == "consensus",mycol]
  nonev = df[df$diag_group == "none",mycol]
  novelv = df[df$diag_group == "novel",mycol]
  conCI <- meanbootCI(conv,nsim = nsim)
  novelCI <- meanbootCI(novelv,nsim = nsim)
  noneCI <- meanbootCI(nonev,nsim = nsim)
  allCIs <- c(conCI,novelCI,noneCI)
  return(allCIs)
}

getCIs <- function(mycol,df,nsim = 100){
  conv = df[df$diag_group == "consensus",mycol]
  nonev = df[df$diag_group == "none",mycol]
  novelv = df[df$diag_group == "novel",mycol]
  discv = df[df$diag_group == "discordant",mycol]
  
  conCI <- bootRatioCI(conv,nonev,nsim = nsim)
  novelCI <- bootRatioCI(novelv,nonev,nsim = nsim)
  discCI <- bootRatioCI(discv,nonev,nsim = nsim)
  allCIs <- c(conCI,novelCI,discCI)
  return(allCIs)
}
```

```{r, message=FALSE}
# load required libraries
library(data.table)
library(ggplot2)
library(RColorBrewer)

#color palette 
myColors <- c("black", '#56B4E9', "gray", "#E69F00")
names(myColors) <- c('consensus', 'discordant', 'none', 'novel')
colScale <- scale_colour_manual(name = "diag_group",values = myColors)

# filepaths
resfile <- "../input/extended_denovoWEST_results.tab"
features <-'../input/gene_features.tab'
```

# Figure 2 (b)  

```{r}
#read in results
res<- fread(resfile,sep = "\t")
res <- res[,c("symbol","diag_group","sig")]
#read in feature file
feat <- fread(features,sep = "\t",header = T)
#merge these
allfeat <- as.data.frame(merge(res,feat,by = c("symbol")))

#names of features in both dataframe and used for plotting
all_feat_terms <- c("dNdS_macaque","CODING_GERP","PROMOTER_GERP","glen","cancer_gene",
               "PPI_DGR","PPI_BTWN","PPI_LLS2HI",
               "median_fetalbrain_rpkm","relevant_go","pLI")
forplot_terms <- c("Macaque dN/dS","coding GERP","promoter GERP","CDS length","Somatic Driver Gene",
                   "Network Degree","Network Betweeness","Network Distance to consensus DD gene",
                   "Median RPKM fetal brain","Relevant GO term","pLI")

#get mean across features by diagnostic group
diag.means <- aggregate(allfeat[,all_feat_terms], list(allfeat$diag_group), mean,na.rm = T)
#calculate how enriched these are compared to 'none' diagnostic group
diag.enrich <- sweep(diag.means[,2:12],MARGIN = 2, FUN = "/", STATS = t(diag.means[3,2:12]))
diag.enrich <- t(diag.enrich)[,c(1,4,2)]
colnames(diag.enrich)<- diag.means$Group.1[c(1,4,2)]

#bootstrap confidence intervals here
nsim = 100
allcis <- sapply(all_feat_terms,FUN = getCIs,df = as.data.frame(allfeat),nsim = nsim)
rownames(allcis) <- c("con.lower","con.upper","novel.lower","novel.upper","disc.lower","disc.upper")
diag.enrich <- cbind(diag.enrich,t(allcis))
rownames(diag.enrich) <- forplot_terms
diag.enrich <- diag.enrich[order(diag.enrich[,1],decreasing = T),]
diag.enrich <- log10(diag.enrich)

#colors for plot
myColors <- c("black", '#56B4E9', "gray", "#E69F00")

#plot consensus vs novel features

#change order to be more readable
diag.enrich <- diag.enrich[c(1,2,3,4,5,10,6,7,8,9,11),]

#pdf("./plots/fig2b.pdf",width = 6,height = 11)
par(mar=c(21,4,2,2)+0.1)
bp <- barplot(t(as.table(diag.enrich[,1:2])),beside = T,las = 3, col = myColors[c(1,4)],ylab = "Log10(Mean in Diagnostic group/Mean in non-DD genes)",ylim = c(min(diag.enrich),max(diag.enrich)),border = NA,cex.axis = 1.2,cex.lab = 1.4,cex.names = 1.2)
abline(h = 0,lty = 2)
arrows(bp[1,],diag.enrich[,colnames(diag.enrich) == "con.lower"],bp[1,],diag.enrich[,colnames(diag.enrich) == "con.upper"],length = 0,col = "grey")
arrows(bp[2,],diag.enrich[,colnames(diag.enrich) == "novel.lower"],bp[2,],diag.enrich[,colnames(diag.enrich) == "novel.upper"],length = 0,col = "grey")
#dev.off()
#to plot legend
#plot(0,0,xaxt = "n",bty = "n",col = "white",xlab = "",ylab = "",yaxt = "n")
#legend("top",legend = c("consensus","novel"),col = myColors[c(1,4)],pch = 15, border = NA,bty = "n",horiz = F, #inset=c(-0.2,0),xpd=TRUE)
```
