---
title: "Figure3"
author: "Joanna Kaplanis and Kaitlin Samocha"
date: "22/08/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, message=FALSE}
# load required libraries
library(data.table)
library(ggplot2)
library(dplyr)
library(tidyr)
library(rateratio.test)
library(wesanderson)
library(ggbeeswarm)

# filepaths
resfile <- "../input/extended_denovoWEST_results.tab"
usfile <- "../input/USabnormality_likelihood.csv"
ddg2p_file = '../input/DDG2P_22_9_2019.csv.gz'
```

```{r}
# load results file
res <- fread(resfile,sep = "\t")
```

#Figure 3(a)  

```{r}
mypal = wes_palette("Zissou1")
res$cat <- NA
res$cat[res$diag_group == "consensus" | res$sig] <- "associated"
res$cat[res$diag_group == "none"] <- "unassociated"
res_nodisc <- res[!is.na(res$cat)]

wilcox.test(res_nodisc$p_lof[res_nodisc$cat == "unassociated"],res_nodisc$p_lof[res_nodisc$cat == "associated"])$p.value

#pdf("fig3a.pdf",width = 6,height = 5.5)
ggplot(res_nodisc[!is.na(res_nodisc$p_lof)],aes(x = cat,y = log10(p_lof),fill = cat)) +
  geom_violin(draw_quantiles = c(0.5) )+
  theme_classic() +
  labs(x = "",y = "log10(PTV mutability)") +
  scale_fill_manual(values=c(mypal[5],mypal[1]),labels = c("significant","not significant")) +
  theme(legend.position="none",legend.title = element_blank(),legend.text = element_text(size = 14),axis.text=element_text(size=14),axis.title=element_text(size=16), axis.line.x = element_blank(), axis.ticks.x = element_blank()) 
#dev.off()
```

#Figure 3(b)   

```{r}
higenes <- res[res$lofe<=10^(-6) & res$sig,]

higenes$lglofratio <- log10(higenes$lofratio)

wilcox.test(higenes$lofratio[higenes$diag_group == "novel"],higenes$lofratio[higenes$diag_group == "consensus"])

p <- ggplot(higenes, aes(x=diag_group, y=lglofratio, fill = diag_group)) + labs(y = "log10(obs/exp PTVs)") + 
  geom_boxplot(notch = F,color = "gray40") + scale_fill_manual(values = c("black", '#56B4E9', "#E69F00")) + 
  theme_classic() +theme(legend.position = "none")+
  #geom_jitter(position = position_jitter(0.1),color = "gray40") +
  xlab("")+ geom_beeswarm(aes(color = group),priority = 'ascending',color = "gray40",cex = 1.8)+
  theme(axis.text=element_text(size=14),axis.title=element_text(size=16), axis.line.x = element_blank(), axis.ticks.x = element_blank()) 
dat <- ggplot_build(p)$data[[1]]

#pdf("fig3b.pdf",width = 6,height = 5.5)
p
#dev.off()
```

#Figure 3(c)  

```{r}
# determine bins
res %>%
  filter(lofe < 1e-6 & constraint_flag=='' & !(symbol %in% c('DNMT3A', 'ASXL1', 'PPM1D', 'TET2'))) %>%
  summarize(max = max(log10(lofratio)), min = min(log10(lofratio)), diff = max(log10(lofratio))-min(log10(lofratio)), steps = (max(log10(lofratio))-min(log10(lofratio)))/5)
```

```{r}
# find ptv and syn counts per bin
ptv_syn_gnomad <- res %>%
  filter(lofe < 1e-6 & constraint_flag=='' & !(symbol %in% c('DNMT3A', 'ASXL1', 'PPM1D', 'TET2'))) %>%
  mutate(lofbin = case_when(log10(lofratio) < 0.9618719+(1*0.3442909) ~ 1,
                            log10(lofratio) < 0.9618719+(2*0.3442909) & log10(lofratio) >= 0.9618719+(1*0.3442909) ~ 2,
                            log10(lofratio) < 0.9618719+(3*0.3442909) & log10(lofratio) >= 0.9618719+(2*0.3442909) ~ 3,
                            log10(lofratio) < 0.9618719+(4*0.3442909) & log10(lofratio) >= 0.9618719+(3*0.3442909) ~ 4,
                            log10(lofratio) >= 0.9618719+(4*0.3442909) ~ 5)) %>%
  group_by(lofbin) %>%
  summarise(genes = n(), ptv = sum(obs_lof), syn = sum(obs_syn), ptv_syn = sum(obs_lof)/sum(obs_syn)) %>%
  ungroup()

ptv_syn_gnomad$lower_bound <- apply(ptv_syn_gnomad, 1, function(row) rateratio.test(c(as.numeric(row[3]), as.numeric(row[4])), c(as.numeric(row[2]), as.numeric(row[2])))$conf[1])
ptv_syn_gnomad$upper_bound <- apply(ptv_syn_gnomad, 1, function(row) rateratio.test(c(as.numeric(row[3]), as.numeric(row[4])), c(as.numeric(row[2]), as.numeric(row[2])))$conf[2])

ptv_syn_gnomad
```

```{r}
# weighted regression
fit_weighted_lofbin_ptvsyn <- glm(ptv_syn ~ lofbin, data=ptv_syn_gnomad, weights = genes)
weighted_intercept <- fit_weighted_lofbin_ptvsyn$coefficients[[1]]
weighted_slope <- fit_weighted_lofbin_ptvsyn$coefficients[[2]]

summary(fit_weighted_lofbin_ptvsyn)
```

```{r, fig.align='center'}
#pdf("fig3c.pdf",width = 7,height = 5)
ggplot(ptv_syn_gnomad, aes(x = lofbin, y = ptv_syn)) +
  geom_point(size=5) +
  theme_classic() +
  ylim(c(0,0.021)) +
  geom_errorbar(aes(ymin=lower_bound, ymax=upper_bound), width=.1) +
  labs(x='PTV enrichment bin', y = 'PTV/syn in gnomAD') +
  geom_abline(intercept = weighted_intercept, slope = weighted_slope, col='darkgray', linetype=2) +
  theme(axis.text.x  = element_text(size=14), axis.text.y = element_text(size=14), axis.title = element_text(size=16)) +
  scale_x_continuous(name = 'PTV enrichment bin', breaks = seq(1,5,1), labels = c('0.96-1.30\n(n=21)', '1.30-1.65\n(n=63)', '1.65-2.00\n(n=40)', '2.00-2.34\n(n=23)', '2.34-2.68\n(n=9)'))
#dev.off()
```

#Figure 3(d)  

```{r}
traffic <- c("#4CBB17","#FF7800","#E60000")

#get a list of known haploinsuffient genes from DDG2P
ddg2p <- fread(ddg2p_file,sep = ",",header = T)
ddg2p <- ddg2p[ddg2p$`DDD category`%in%c("probable","confirmed") & ddg2p$`allelic requirement` %in% c("monoallelic", 'x-linked dominant'),c("gene symbol","hgnc id","DDD category","allelic requirement","mutation consequence")]
ddg2p <- unique(ddg2p)
see<- ddg2p[,.( mutconsqs = paste(`mutation consequence`,collapse = "|")),by = .(`gene symbol`,`hgnc id`,`DDD category`,`allelic requirement`)]
ddg2p <- unique(see)
lof_ddg2p <- ddg2p[grepl('loss of function',ddg2p$mutconsqs),]

#read in fetal class file with likelihood of US abnormality
cl <- fread(usfile,sep = ",")
cl$lik_anomaly <- cl$`Likelihood of anomalies identified on antenatal USS`

#merge this with results file
clinfo <- merge(cl,res,by.x = c("Symbol"),by.y = c("symbol"),all.x = T)

#only include known haploinsufficent
clinfo <- clinfo[clinfo$Symbol %in% lof_ddg2p$`gene symbol`]
clinfo <- clinfo[!is.na(clinfo$lofexpected),]

#calcuated expected and observed across three classes
expcounts <- aggregate(clinfo$lofexpected,by = list(clinfo$lik_anomaly),FUN = sum,na.rm = T)
obscounts <- aggregate(clinfo$lofcount,by = list(clinfo$lik_anomaly),FUN = sum,na.rm = T)

poisson.test(c(obscounts$x[obscounts$Group.1 == 1],sum(obscounts$x[obscounts$Group.1 != 1])),T =  c(expcounts$x[expcounts$Group.1 == 1],sum(expcounts$x[expcounts$Group.1 != 1])))

#confidence intervals
ci.lower <- sapply(obscounts$x, function(x) poisson.test(x,conf.level = 0.95)$conf.int[1])/expcounts$x
ci.upper <- sapply(obscounts$x, function(x) poisson.test(x,conf.level = 0.95)$conf.int[2])/expcounts$x

# combine
abnormal_us_obs_exp <- merge(obscounts, expcounts, by = 'Group.1')
colnames(abnormal_us_obs_exp) <- c('Group', 'observed', 'expected')

# plot
#pdf("fig3d.pdf",width = 5,height = 5)
ggplot(abnormal_us_obs_exp, aes(x=Group, y=observed/expected)) +
  geom_bar(stat='identity', fill=traffic) +
  theme_classic() +
  ylim(c(0,60)) +
  labs(y = 'PTV enrichment') +
  scale_x_continuous(name="Genes' likelihood of ultrasound abnormality", breaks = seq(1,3,1), labels=c("low","medium","high")) +
  theme(axis.text.x  = element_text(size=14, vjust = 3), axis.text.y = element_text(size=14), axis.title = element_text(size=16), axis.line.x = element_blank(), axis.ticks.x = element_blank()) +
  geom_segment(aes(x=c(1,2,3), y=ci.lower, xend=c(1,2,3), yend=ci.upper))
#dev.off()

```

# Putting the plots together  

```{r}
library(cowplot)
# saving plots
plot_3a <- ggplot(respow[!is.na(respow$cat),],aes(x = cat,y = powmed,fill = sig)) +
  geom_boxplot() +
  theme_classic() +
  labs(x = "",y = "Power (using median enrichment)") +
  scale_fill_manual(values=c(mypal[5],mypal[1]),labels = c("not significant","significant")) +
  theme(legend.position="top",legend.title = element_blank(),legend.text = element_text(size = 14),axis.text=element_text(size=14),axis.title=element_text(size=16), axis.line.x = element_blank(), axis.ticks.x = element_blank())

plot_3b <- p

plot_3c <- ggplot(ptv_syn_gnomad, aes(x = lofbin, y = ptv_syn)) +
  geom_point(size=5) +
  theme_classic() +
  ylim(c(0,0.021)) +
  geom_errorbar(aes(ymin=lower_bound, ymax=upper_bound), width=.1) +
  labs(x='PTV enrichment bin', y = 'PTV/syn in gnomAD') +
  geom_abline(intercept = weighted_intercept, slope = weighted_slope, col='darkgray', linetype=2) +
  theme(axis.text.x  = element_text(size=14), axis.text.y = element_text(size=14), axis.title = element_text(size=16)) +
  scale_x_continuous(name = 'PTV enrichment bin', breaks = seq(1,5,1), labels = c('0.96-1.30\n(n=21)', '1.30-1.65\n(n=63)', '1.65-2.00\n(n=40)', '2.00-2.34\n(n=23)', '2.34-2.68\n(n=9)'))

plot_3d <- ggplot(abnormal_us_obs_exp, aes(x=Group, y=observed/expected)) +
  geom_bar(stat='identity', fill=traffic) +
  theme_classic() +
  ylim(c(0,60)) +
  labs(y = 'PTV enrichment') +
  scale_x_continuous(name="Genes' likelihood of ultrasound abnormality", breaks = seq(1,3,1), labels=c("low","medium","high")) +
  theme(axis.text.x  = element_text(size=14, vjust = 3), axis.text.y = element_text(size=14), axis.title = element_text(size=16), axis.line.x = element_blank(), axis.ticks.x = element_blank()) +
  geom_segment(aes(x=c(1,2,3), y=ci.lower, xend=c(1,2,3), yend=ci.upper))

#pdf("combined_fig3.pdf",width = 12, height = 8)
top_row <- plot_grid(plot_3a, plot_3b, labels=c('(a)', '(b)'), scale=0.95)
bottom_row <- plot_grid(plot_3c, plot_3d, nrow = 1, labels = c('(c)', '(d)'), rel_widths = c(1.5, 1), scale=0.95)
plot_grid(top_row, bottom_row, nrow = 2)
#dev.off()
```
